version: '2.0'

services:
  postgresdb:
    restart: always
    image: postgres
    env_file:
      - settings/databases.environ
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shopnet

  redishost:
    image: redis
    volumes:
      - 'redisdata:/data'
    networks:
      - shopnet

  elasticsearch:
    image: elasticsearch:1.7.5
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - shopnet

  wsgiapp:
    restart: always
    image: bombayshop
    environment:
      - POSTGRES_DB=myshop_bombay
      - DJANGO_SETTINGS_MODULE=myshop.settings
#      - DJANGO_DEBUG=1
      - VIRTUAL_HOST=bombayshop.com.ua,www.bombayshop.com.ua
      - VIRTUAL_PROTO=uwsgi
      - VIRTUAL_PORT=9009
      - LETSENCRYPT_HOST=bombayshop.com.ua,www.bombayshop.com.ua
      - LETSENCRYPT_EMAIL=ssladmin@bombayshop.com.ua
    env_file:
      - settings/databases.environ
    volumes:
      - shopmedia:/web/media
      - /root/settings/uwsgi.ini:/web/uwsgi.ini
    command: uwsgi --ini uwsgi.ini
    depends_on:
      - postgresdb
      - redishost
      - elasticsearch
    networks:
      - shopnet
    ports:
      - 9009:9009

  worker:
    restart: always
    image: bombayshop
    environment:
      - POSTGRES_DB=myshop_bombay
      - DJANGO_SETTINGS_MODULE=myshop.settings
    env_file:
      - settings/databases.environ
      - settings/email.environ
    volumes:
      - shopmedia:/web/media
      - /root/settings/uwsgi.ini:/web/uwsgi.ini
    command: su django -c /web/worker.py
    depends_on:
      - postgresdb
      - redishost
    networks:
      - shopnet

  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /root/ssl:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - shopmedia:/app/media
    depends_on:
      - wsgiapp
    networks:
      - shopnet
      - nginx-proxy
    ports:
      - 80:80
      - 443:443

networks:
  shopnet:
  nginx-proxy:
    external: true

volumes:
  pgdata:
  redisdata:
  shopmedia:
  esdata:

