version: '2.0'

services:
  postgresdb:
    restart: always
    image: postgres
    env_file:
      - settings/databases.environ
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shopnet

  redishost:
    image: redis
    volumes:
      - 'redisdata:/data'
    networks:
      - shopnet

  elasticsearch:
    image: elasticsearch:1.7.5
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - shopnet

  wsgiapp:
    restart: always
    image: bombayshop
    environment:
      - DJANGO_DEBUG=0
      - POSTGRES_DB=myshop_bombay
      - DJANGO_SETTINGS_MODULE=myshop.settings
      - VIRTUAL_HOST=www.bombayshop.com.ua
      - VIRTUAL_PROTO=uwsgi
      - LETSENCRYPT_HOST=www.bombayshop.com.ua
      - LETSENCRYPT_EMAIL=ssladmin@bombayshop.com.ua
    env_file:
      - settings/databases.environ
    volumes:
      - shopmedia:/web/workdir
      - ./bombay.json:/web/fixtures/bombay.json
    command: uwsgi --ini uwsgi.ini
    depends_on:
      - postgresdb
      - redishost
      - elasticsearch
    networks:
      - shopnet
      - nginx-proxy

  worker:
    restart: always
    image: bombayshop
    environment:
      - DJANGO_DEBUG=1
      - POSTGRES_DB=myshop_bombay
      - DJANGO_SETTINGS_MODULE=myshop.settings
    env_file:
      - settings/databases.environ
      - settings/email.environ
    command: su django -c /web/worker.py
    volumes:
      - shopmedia:/web/workdir
      - ./bombay.json:/web/fixtures/bombay.json
    depends_on:
      - postgresdb
      - redishost
    networks:
      - shopnet

networks:
  shopnet:
  nginx-proxy:
      external: true

volumes:
  pgdata:
  redisdata:
  shopmedia:
  esdata:

