# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-17 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import djangocms_text_ckeditor.fields
import parler.models
import shop.money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200701_1302'),
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshop.Product')),
                ('unit_price', shop.money.fields.MoneyField(decimal_places=3, help_text='Net price for this product', verbose_name='Unit price')),
                ('discounted_price', shop.money.fields.MoneyField(decimal_places=3, help_text='Price for this product after applying a discount.', verbose_name='Discounted price')),
                ('product_code', models.CharField(max_length=255, unique=True, verbose_name='Product code')),
                ('gender', models.CharField(choices=[('m', 'Men'), ('w', 'Women')], max_length=15, verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'Clothes',
                'verbose_name_plural': 'Clothes',
            },
            bases=('myshop.product',),
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClothesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(help_text="Full description used in the catalog's detail view of Clothes.", verbose_name='Description')),
                ('color', models.CharField(blank=True, help_text='Color of product', max_length=255, null=True, verbose_name='Color of product')),
                ('fabric', models.CharField(blank=True, help_text='Fabric of product', max_length=255, null=True, verbose_name='Fabric of product')),
                ('composition', models.CharField(blank=True, help_text='Composition of product material', max_length=255, null=True, verbose_name='Composition of product material')),
                ('decoration', models.CharField(blank=True, help_text='Decoration and features', max_length=255, null=True, verbose_name='Decoration and features')),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], help_text='Condition of product', max_length=255, null=True, verbose_name='Condition of product')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multilingual', to='myshop.Clothes')),
            ],
            options={
                'db_tablespace': '',
                'default_permissions': (),
                'db_table': 'myshop_clothes_translation',
                'verbose_name': 'Clothes Translation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClothesVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.PositiveIntegerField(choices=[(44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67)], help_text='Size of Item', verbose_name='Product size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='myshop.Clothes', verbose_name='Clothes name')),
            ],
        ),
        migrations.CreateModel(
            name='CountryOfOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Country of origin',
                'verbose_name_plural': 'Countries of origin',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CountryOfOriginTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Country of origin')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='myshop.CountryOfOrigin')),
            ],
            options={
                'db_tablespace': '',
                'default_permissions': (),
                'db_table': 'myshop_countryoforigin_translation',
                'verbose_name': 'Country of origin Translation',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not available'), ('on_order', 'On Order'), ('avaiting_delivery', 'Avaiting Delivery')], default='available', max_length=50, verbose_name='Availability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='product_name',
            field=models.CharField(default='test', max_length=255, verbose_name='Product Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myshop.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='smartcard',
            name='speed',
            field=models.CharField(choices=[('4', '4 MB/s'), ('20', '20 MB/s'), ('30', '30 MB/s'), ('40', '40 MB/s'), ('48', '48 MB/s'), ('80', '80 MB/s'), ('95', '95 MB/s'), ('280', '280 MB/s')], max_length=8, verbose_name='Transfer Speed'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myshop.CountryOfOrigin', verbose_name='Country of origin'),
        ),
        migrations.AlterUniqueTogether(
            name='countryoforigintranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='clothestranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
