# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-17 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_auto_20190217_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], default='summer', max_length=15, verbose_name='Seson'),
            preserve_default=False,
        ),
    ]
