# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-17 19:34
from __future__ import unicode_literals

from django.db import migrations
import shop.money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_clothes_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='clothes',
            name='price_without_discount',
            field=shop.money.fields.MoneyField(default='465', help_text='Price for this product without applying a discount.', verbose_name='Price without discount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothes',
            name='unit_price',
            field=shop.money.fields.MoneyField(help_text='Net price for this product', verbose_name='Unit price'),
        ),
    ]
