# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models.address


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_auto_20190217_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address_text',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address2',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='region',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='region',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=shop.models.address.CountryField(choices=[('UA', 'Ukraine')], verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ZIP / Postal code'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=shop.models.address.CountryField(choices=[('UA', 'Ukraine')], verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ZIP / Postal code'),
        ),
    ]
