# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_auto_20190218_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address_text',
            field=models.TextField(blank=True, help_text='Billing address at the moment of purchase.', null=True, verbose_name='Billing Address'),
        ),
    ]
