# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_order_billing_address_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='billing_address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='myshop.BillingAddress'),
        ),
    ]
