# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-04 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import shop.money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_cart_billing_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(help_text="Full description used in the catalog's detail view of Commodity.", verbose_name='Description')),
                ('color', models.CharField(blank=True, help_text='Color and shades of product', max_length=255, null=True, verbose_name='Color and shades of product')),
                ('hair_type', models.CharField(blank=True, help_text='Type of hair', max_length=255, null=True, verbose_name='Type of hair')),
                ('classification', models.CharField(blank=True, help_text='Classification of the commodityl', max_length=255, null=True, verbose_name='Classification of the commodity')),
                ('package', models.CharField(blank=True, help_text='Package', max_length=255, null=True, verbose_name='Package')),
                ('weight', models.CharField(blank=True, help_text='Weight/Volume', max_length=100, null=True, verbose_name='Weight/Volume')),
            ],
            options={
                'verbose_name': 'Commodity Translation',
                'managed': True,
                'db_table': 'myshop_commodity_translation',
                'default_permissions': (),
                'db_tablespace': '',
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='price_without_discount',
            field=shop.money.fields.MoneyField(default=0, help_text='Price for this product without applying a discount.', verbose_name='Price without discount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='salutation',
            field=models.CharField(blank=True, choices=[('mrs', 'Mrs.'), ('mr', 'Mr.'), ('na', '(n/a)')], max_length=5, null=True, verbose_name='Salutation'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='commoditytranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multilingual', to='myshop.Commodity'),
        ),
        migrations.AlterUniqueTogether(
            name='commoditytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
