# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-20 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_cart_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(default='123', max_length=30, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
