# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-20 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0009_auto_20190220_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone',
        ),
    ]
