# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('myshop', '0009_auto_20190304_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('whole_year', 'Whole year')], max_length=15, verbose_name='Seson'),
        ),
        migrations.AlterField(
            model_name='clothesvariant',
            name='product_size',
            field=models.PositiveIntegerField(choices=[(40, 40), (42, 42), (44, 44), (46, 46), (48, 48), (50, 50), (52, 52), (54, 54), (56, 56), (58, 58), (60, 60), (62, 62), (64, 64), (66, 66), (68, 68)], help_text='Size of Item', verbose_name='Product size'),
        ),
    ]
