# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_auto_20190220_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='salutation',
            field=models.CharField(blank=True, choices=[('mrs', 'Mrs.'), ('mr', 'Mr.'), ('na', '(n/a)')], max_length=5, null=True, verbose_name='Salutation'),
        ),
    ]
