# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0011_auto_20190312_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_option',
            field=models.CharField(blank=True, choices=[('best_seller', 'Available'), ('sale', 'Not available'), ('new_product', 'On Order'), ('best_price', 'Avaiting Delivery')], max_length=50, null=True, verbose_name='Promo option'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='season',
            field=models.CharField(choices=[('spring-summer-fall', 'Spring, Summer, Fall'), ('winter', 'Winter'), ('whole_year', 'Whole year')], max_length=15, verbose_name='Seson'),
        ),
    ]
