# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-02 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import shop.money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0011_auto_20190222_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(help_text="Full description used in the catalog's detail view of Commodity.", verbose_name='Description')),
                ('color', models.CharField(blank=True, help_text='Color and sades of product', max_length=255, null=True, verbose_name='Color and sades of product')),
                ('hair_type', models.CharField(blank=True, help_text='Type of hair', max_length=255, null=True, verbose_name='Type of hair')),
                ('classification', models.CharField(blank=True, help_text='Classification of the commodityl', max_length=255, null=True, verbose_name='Classification of the commodity')),
                ('package', models.CharField(blank=True, help_text='Package', max_length=255, null=True, verbose_name='Package')),
                ('weight', models.CharField(blank=True, help_text='Weight/Volume', max_length=100, null=True, verbose_name='Weight/Volume')),
            ],
            options={
                'managed': True,
                'db_tablespace': '',
                'db_table': 'myshop_commodity_translation',
                'default_permissions': (),
                'verbose_name': 'Commodity Translation',
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='price_without_discount',
            field=shop.money.fields.MoneyField(default=0, help_text='Price for this product without applying a discount.', verbose_name='Price without discount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commoditytranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multilingual', to='myshop.Commodity'),
        ),
        migrations.AlterUniqueTogether(
            name='commoditytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
