# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0012_auto_20190315_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='season',
            field=models.CharField(choices=[('spring-summer-fall', 'Spring, Summer, Fall'), ('winter', 'Winter'), ('whole_year', 'Whole year')], max_length=30, verbose_name='Seson'),
        ),
    ]
