# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0012_auto_20190302_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditytranslation',
            name='color',
            field=models.CharField(blank=True, help_text='Color and shades of product', max_length=255, null=True, verbose_name='Color and shades of product'),
        ),
    ]
