# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-03 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0013_auto_20190302_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Full name'),
        ),
    ]
