# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0013_auto_20190315_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promo_option',
            field=models.CharField(blank=True, choices=[('best_seller', 'Best Seller'), ('sale', 'Sale'), ('new_product', 'New Product'), ('best_price', 'Best Price')], max_length=50, null=True, verbose_name='Promo option'),
        ),
    ]
