# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-22 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import djangocms_text_ckeditor.fields
import shop.money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0014_auto_20190319_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalClothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshop.Product')),
                ('unit_price', shop.money.fields.MoneyField(help_text='Net price for this product', verbose_name='Unit price')),
                ('price_without_discount', shop.money.fields.MoneyField(help_text='Price for this product without applying a discount.', verbose_name='Price without discount')),
                ('product_code', models.CharField(max_length=255, unique=True, verbose_name='Product code')),
                ('gender', models.CharField(choices=[('m', 'Men'), ('w', 'Women')], max_length=15, verbose_name='Gender')),
                ('season', models.CharField(choices=[('spring-summer-fall', 'Spring, Summer, Fall'), ('winter', 'Winter'), ('whole_year', 'Whole year')], max_length=30, verbose_name='Seson')),
            ],
            options={
                'verbose_name': 'Universal Clothes',
                'verbose_name_plural': 'Universal Clothes',
            },
            bases=('myshop.product',),
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UniversalClothesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(help_text="Full description used in the catalog's detail view of Clothes.", verbose_name='Description')),
                ('color', models.CharField(blank=True, help_text='Color of product', max_length=255, null=True, verbose_name='Color of product')),
                ('fabric', models.CharField(blank=True, help_text='Fabric of product', max_length=255, null=True, verbose_name='Fabric of product')),
                ('composition', models.CharField(blank=True, help_text='Composition of product material', max_length=255, null=True, verbose_name='Composition of product material')),
                ('decoration', models.CharField(blank=True, help_text='Decoration and features', max_length=255, null=True, verbose_name='Decoration and features')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multilingual', to='myshop.UniversalClothes')),
            ],
            options={
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'db_table': 'myshop_universalclothes_translation',
                'verbose_name': 'Universal Clothes Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='universalclothestranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
